export const menu = [
  {
    name: 'Dashboard',
    path: 'dashboard',
    redirect: '/dashboard/workplace',
    type: 0,
    component: '#',
    sort: 0,
    status: true,
    permissionList: [],
    meta: {
      title: 'router.dashboard',
      icon: 'ant-design:dashboard-outlined',
      hidden: false,
      affix: false,
      activeMenu: false,
      alwaysShow: false,
      breadcrumb: true,
      canTo: false,
      noCache: false,
      noTagsView: false,
    },
    children: [
      {
        name: 'Workplace',
        path: 'workplace',
        redirect: null,
        type: 1,
        component: 'views/Dashboard/Workplace',
        sort: 0,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.workplace',
          icon: 'mdi:facebook-workplace',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Analysis',
        path: 'analysis',
        redirect: null,
        type: 1,
        component: 'views/Dashboard/Analysis',
        sort: 1,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.analysis',
          icon: 'uil:statistics',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
    ],
  },
  {
    name: 'Authorization',
    path: 'authorization',
    redirect: '/authorization/user',
    type: 0,
    component: '#',
    sort: 1,
    status: true,
    permissionList: [],
    meta: {
      title: 'router.authorization',
      icon: 'fluent-mdl2:permissions',
      hidden: false,
      affix: false,
      activeMenu: false,
      alwaysShow: false,
      breadcrumb: true,
      canTo: false,
      noCache: false,
      noTagsView: false,
    },
    children: [
      {
        name: 'Department',
        path: 'department',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Department/Department',
        sort: 0,
        status: true,
        permissionList: [
          {
            name: '新增',
            code: 'add',
            value: null,
            resource: 'department',
          },
          {
            name: '编辑',
            code: 'update',
            value: null,
            resource: 'department',
          },
          {
            name: '删除',
            code: 'delete',
            value: null,
            resource: 'department',
          },
          {
            name: '查看',
            code: 'view',
            value: null,
            resource: 'department',
          },
          {
            name: '种子数据',
            code: 'seed',
            value: null,
            resource: 'department',
          },
        ],
        meta: {
          title: 'router.department',
          icon: 'mingcute:department-line',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Dictionary',
        path: 'dictionary',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Dictionary/Dictionary',
        sort: 1,
        status: true,
        permissionList: [
          {
            name: '新增',
            code: 'add',
            value: null,
            resource: 'dictionary',
          },
          {
            name: '编辑',
            code: 'update',
            value: null,
            resource: 'dictionary',
          },
          {
            name: '删除',
            code: 'delete',
            value: null,
            resource: 'dictionary',
          },
          {
            name: '查看',
            code: 'view',
            value: null,
            resource: 'dictionary',
          },
          {
            name: '种子数据',
            code: 'seed',
            value: null,
            resource: 'dictionary',
          },
        ],
        meta: {
          title: 'router.dictionary',
          icon: 'qlementine-icons:dictionary-16',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'User',
        path: 'user',
        redirect: null,
        type: 1,
        component: 'views/Authorization/User/User',
        sort: 2,
        status: true,
        permissionList: [
          {
            name: '新增',
            code: 'add',
            value: null,
            resource: 'user',
          },
          {
            name: '编辑',
            code: 'update',
            value: null,
            resource: 'user',
          },
          {
            name: '删除',
            code: 'delete',
            value: null,
            resource: 'user',
          },
          {
            name: '查看',
            code: 'view',
            value: null,
            resource: 'user',
          },
        ],
        meta: {
          title: 'router.userIdentity',
          icon: 'solar:user-linear',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Menu',
        path: 'menu',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Menu/Menu',
        sort: 3,
        status: true,
        permissionList: [
          {
            name: '新增',
            code: 'add',
            value: null,
            resource: 'menu',
          },
          {
            name: '删除',
            code: 'delete',
            value: null,
            resource: 'menu',
          },
          {
            name: '查看',
            code: 'view',
            value: null,
            resource: 'menu',
          },
          {
            name: '更新',
            code: 'update',
            value: null,
            resource: 'menu',
          },
          {
            name: '刷新菜单',
            code: 'refresh',
            value: null,
            resource: 'menu',
          },
          {
            name: '种子数据',
            code: 'seed',
            value: null,
            resource: 'menu',
          },
        ],
        meta: {
          title: 'router.menuManagement',
          icon: 'lucide:square-menu',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: true,
          noTagsView: false,
        },
      },
      {
        name: 'Role',
        path: 'role',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Role/Role',
        sort: 4,
        status: true,
        permissionList: [
          {
            name: '新增',
            code: 'add',
            value: null,
            resource: 'role',
          },
          {
            name: '编辑',
            code: 'update',
            value: null,
            resource: 'role',
          },
          {
            name: '删除',
            code: 'delete',
            value: null,
            resource: 'role',
          },
          {
            name: '查看',
            code: 'view',
            value: null,
            resource: 'role',
          },
          {
            name: '生成种子',
            code: 'seed',
            value: null,
            resource: 'role',
          },
        ],
        meta: {
          title: 'router.role',
          icon: 'oui:app-users-roles',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
    ],
  },
  {
    name: 'Personal',
    path: 'personal',
    redirect: '/persoanl/information',
    type: 0,
    component: '#',
    sort: 2,
    status: true,
    permissionList: [
      {
        name: '新增',
        code: 'add',
        value: null,
        resource: 'personal',
      },
      {
        name: '编辑',
        code: 'update',
        value: null,
        resource: 'personal',
      },
      {
        name: '删除',
        code: 'delete',
        value: null,
        resource: 'personal',
      },
      {
        name: '查看',
        code: 'view',
        value: null,
        resource: 'role',
      },
    ],
    meta: {
      title: 'router.personalCenter',
      icon: 'vi-ant-design:user-outlined',
      hidden: false,
      affix: false,
      activeMenu: false,
      alwaysShow: false,
      breadcrumb: true,
      canTo: false,
      noCache: false,
      noTagsView: false,
    },
    children: [
      {
        name: 'PersonalCenter',
        path: 'information',
        redirect: null,
        type: 1,
        component: 'views/Personal/PersonalCenter/PersonalCenter',
        sort: 0,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.userInfo',
          icon: 'fluent-mdl2:contact-info',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
    ],
  },
  {
    name: 'System',
    path: 'system',
    redirect: '/system/userLog',
    type: 0,
    component: '#',
    sort: 3,
    status: true,
    permissionList: [],
    meta: {
      title: 'router.systemManagement',
      icon: 'grommet-icons:system',
      hidden: false,
      affix: false,
      activeMenu: false,
      alwaysShow: false,
      breadcrumb: true,
      canTo: false,
      noCache: false,
      noTagsView: false,
    },
    children: [
      {
        name: 'UserList',
        path: 'userList',
        redirect: null,
        type: 1,
        component: 'views/System/UserList/UserList',
        sort: 0,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.userManagement',
          icon: 'solar:user-linear',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'OnlineUser',
        path: 'onlineUser',
        redirect: null,
        type: 1,
        component: 'views/System/OnlineUser/OnlineUser',
        sort: 0,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.onlineUser',
          icon: 'solar:user-linear',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Oss',
        path: 'oss',
        redirect: null,
        type: 1,
        component: 'views/System/Oss/Oss',
        sort: 0,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.ossManagement',
          icon: 'eva:file-outline',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'FileList',
        path: 'fileList',
        redirect: null,
        type: 1,
        component: 'views/System/File/FileList',
        sort: 0,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.fileManagement',
          icon: 'eva:file-outline',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'UserLog',
        path: 'userLog',
        redirect: null,
        type: 1,
        component: 'views/System/UserLog/UserLog',
        sort: 0,
        status: true,
        permissionList: [],
        meta: {
          title: 'router.userLog',
          icon: 'octicon:log-24',
          hidden: false,
          affix: false,
          activeMenu: false,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          noCache: false,
          noTagsView: false,
        },
      },
    ],
  },
];
