export const menu = [
  {
    name: 'Dashboard',
    path: 'dashboard',
    component: '#',
    redirect: '/dashboard/workplace',
    sort: 0,
    type: 0,
    children: [
      {
        name: 'Workplace',
        path: 'workplace',
        component: 'views/Dashboard/Workplace',
        redirect: null,
        sort: 0,
        type: 1,
        meta: {
          title: 'router.workplace',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Analysis',
        path: 'analysis',
        component: 'views/Dashboard/Analysis',
        redirect: null,
        sort: 1,
        type: 1,
        meta: {
          title: 'router.analysis',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
    ],
    meta: {
      title: 'router.dashboard',
      icon: 'vi-ant-design:dashboard-filled',
      affix: false,
      activeMenu: null,
      alwaysShow: false,
      breadcrumb: true,
      canTo: false,
      hidden: false,
      noCache: false,
      noTagsView: false,
    },
  },
  {
    name: 'Authorization',
    path: 'authorization',
    component: '#',
    redirect: '/authorization/user',
    sort: 3,
    type: 0,
    children: [
      {
        name: 'Department',
        path: 'department',
        component: 'views/Authorization/Department/Department',
        redirect: null,
        sort: 0,
        type: 1,
        meta: {
          title: 'router.department',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Dictionary',
        path: 'dictionary',
        component: 'views/Authorization/Dictionary/Dictionary',
        redirect: null,
        sort: 1,
        type: 1,
        meta: {
          title: '字典管理',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'User',
        path: 'user',
        component: 'views/Authorization/User/User',
        redirect: null,
        sort: 2,
        type: 1,
        meta: {
          title: '员工管理',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Menu',
        path: 'menu',
        component: 'views/Authorization/Menu/Menu',
        redirect: null,
        sort: 3,
        type: 1,
        meta: {
          title: 'router.menuManagement',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Role',
        path: 'role',
        component: 'views/Authorization/Role/Role',
        redirect: null,
        sort: 4,
        type: 1,
        meta: {
          title: 'router.role',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
    ],
    meta: {
      title: 'router.authorization',
      icon: 'vi-eos-icons:role-binding',
      affix: false,
      activeMenu: null,
      alwaysShow: false,
      breadcrumb: true,
      canTo: false,
      hidden: false,
      noCache: false,
      noTagsView: false,
    },
  },
  {
    name: 'Personal',
    path: 'personal',
    component: '#',
    redirect: '/persoanl/notification',
    sort: 5,
    type: 0,
    children: [
      {
        name: 'PersonalCenter',
        path: 'personal-center',
        component: 'views/Personal/PersonalCenter/PersonalCenter',
        redirect: null,
        sort: 0,
        type: 1,
        meta: {
          title: '个人信息',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
      {
        name: 'Notification',
        path: 'notification',
        component: 'views/Personal/Notification/Notification',
        redirect: null,
        sort: 1,
        type: 1,
        meta: {
          title: '我的通知',
          icon: null,
          affix: false,
          activeMenu: null,
          alwaysShow: false,
          breadcrumb: true,
          canTo: false,
          hidden: false,
          noCache: false,
          noTagsView: false,
        },
      },
    ],
    meta: {
      title: 'router.personalCenter',
      icon: 'vi-ant-design:user-outlined',
      affix: false,
      activeMenu: null,
      alwaysShow: false,
      breadcrumb: true,
      canTo: false,
      hidden: false,
      noCache: false,
      noTagsView: false,
    },
  },
];
